id: I9F6697F5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T19:37:12+00:00'
last_modified: '2022-06-08T16:30:42.079989+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25096
  title: བོད་སོག་གི་རིག་གནས་འབྲེལ་བའི་ཞིབ་འཇུག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    7DE0:
      image_group_id: I1GS55116
      title: ''
      total_pages: 297
      order: 1
      base_file: 7DE0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
