id: P010650
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:18:13.874078
source_metadata:
  id: bdr:W25096
  title: བོད་སོག་གི་རིག་གནས་འབྲེལ་བའི་ཞིབ་འཇུག
  author: ''
  volumes:
    78e7ed68e5f146bb864abc6c0ffc1a32:
      image_group_id: I1GS55116
      title: ''
      volume_number: 1
      total_pages: 297
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
